import '../models/team.dart';
import '../models/match_stat.dart';
import '../models/player.dart';

/// API anahtarı olmadan veya çevrimdışı kullanım için hazır zengin futbol verileri
class MockFootballService {
  static List<Team> getMockTeams() {
    return [
      Team(
        id: '541',
        name: 'Real Madrid',
        shortName: 'Real Madrid',
        crestUrl: 'https://media.api-sports.io/football/teams/541.png',
        league: 'La Liga',
        venue: 'Santiago Bernabéu',
        stats: const MatchStat(
          played: 28,
          won: 21,
          drawn: 5,
          lost: 2,
          goalsScored: 62,
          goalsConceded: 20,
          homePlayed: 14,
          homeWon: 12,
          homeDrawn: 2,
          homeLost: 0,
          homeGoalsScored: 36,
          homeGoalsConceded: 9,
          awayPlayed: 14,
          awayWon: 9,
          awayDrawn: 3,
          awayLost: 2,
          awayGoalsScored: 26,
          awayGoalsConceded: 11,
          avgPossession: 60.5,
          avgShotsPerGame: 16.8,
          avgShotsOnTarget: 6.4,
          cleanSheets: 14,
          recentForm: ['W', 'W', 'W', 'D', 'W'],
        ),
        squad: [
          Player(id: 'rm1', name: 'Vinícius Júnior', position: 'Forvet', goals: 15, assists: 7, matchesPlayed: 24, rating: 8.4),
          Player(id: 'rm2', name: 'Jude Bellingham', position: 'Orta Saha', goals: 18, assists: 8, matchesPlayed: 25, rating: 8.6),
          Player(id: 'rm3', name: 'Kylian Mbappé', position: 'Forvet', goals: 17, assists: 5, matchesPlayed: 23, rating: 8.5),
          Player(id: 'rm4', name: 'Thibaut Courtois', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 15, rating: 7.9, isInjured: true, injuryReason: 'Kas yırtığı (2 hafta)'),
          Player(id: 'rm5', name: 'Antonio Rüdiger', position: 'Defans', goals: 2, assists: 1, matchesPlayed: 26, rating: 7.7),
        ],
      ),
      Team(
        id: '529',
        name: 'FC Barcelona',
        shortName: 'Barcelona',
        crestUrl: 'https://media.api-sports.io/football/teams/529.png',
        league: 'La Liga',
        venue: 'Estadi Olímpic Lluís Companys',
        stats: const MatchStat(
          played: 28,
          won: 19,
          drawn: 4,
          lost: 5,
          goalsScored: 68,
          goalsConceded: 32,
          homePlayed: 14,
          homeWon: 11,
          homeDrawn: 1,
          homeLost: 2,
          homeGoalsScored: 38,
          homeGoalsConceded: 14,
          awayPlayed: 14,
          awayWon: 8,
          awayDrawn: 3,
          awayLost: 3,
          awayGoalsScored: 30,
          awayGoalsConceded: 18,
          avgPossession: 64.2,
          avgShotsPerGame: 15.9,
          avgShotsOnTarget: 6.8,
          cleanSheets: 10,
          recentForm: ['W', 'W', 'L', 'W', 'W'],
        ),
        squad: [
          Player(id: 'fcb1', name: 'Robert Lewandowski', position: 'Forvet', goals: 21, assists: 4, matchesPlayed: 26, rating: 8.3),
          Player(id: 'fcb2', name: 'Lamine Yamal', position: 'Forvet', goals: 9, assists: 12, matchesPlayed: 27, rating: 8.5),
          Player(id: 'fcb3', name: 'Raphinha', position: 'Forvet', goals: 13, assists: 10, matchesPlayed: 25, rating: 8.2),
          Player(id: 'fcb4', name: 'Marc-André ter Stegen', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 8, rating: 7.5, isInjured: true, injuryReason: 'Diz ameliyatı'),
          Player(id: 'fcb5', name: 'Pedri', position: 'Orta Saha', goals: 4, assists: 6, matchesPlayed: 24, rating: 8.0),
        ],
      ),
      Team(
        id: '50',
        name: 'Manchester City',
        shortName: 'Man City',
        crestUrl: 'https://media.api-sports.io/football/teams/50.png',
        league: 'Premier League',
        venue: 'Etihad Stadium',
        stats: const MatchStat(
          played: 29,
          won: 20,
          drawn: 6,
          lost: 3,
          goalsScored: 67,
          goalsConceded: 28,
          homePlayed: 15,
          homeWon: 12,
          homeDrawn: 3,
          homeLost: 0,
          homeGoalsScored: 41,
          homeGoalsConceded: 13,
          awayPlayed: 14,
          awayWon: 8,
          awayDrawn: 3,
          awayLost: 3,
          awayGoalsScored: 26,
          awayGoalsConceded: 15,
          avgPossession: 66.8,
          avgShotsPerGame: 17.5,
          avgShotsOnTarget: 7.1,
          cleanSheets: 11,
          recentForm: ['W', 'D', 'W', 'W', 'W'],
        ),
        squad: [
          Player(id: 'mc1', name: 'Erling Haaland', position: 'Forvet', goals: 24, assists: 3, matchesPlayed: 27, rating: 8.7),
          Player(id: 'mc2', name: 'Kevin De Bruyne', position: 'Orta Saha', goals: 6, assists: 14, matchesPlayed: 20, rating: 8.5),
          Player(id: 'mc3', name: 'Phil Foden', position: 'Forvet', goals: 14, assists: 8, matchesPlayed: 28, rating: 8.2),
          Player(id: 'mc4', name: 'Rodri', position: 'Orta Saha', goals: 7, assists: 6, matchesPlayed: 18, rating: 8.8, isInjured: true, injuryReason: 'Ön çapraz bağ sakatlığı'),
          Player(id: 'mc5', name: 'Rúben Dias', position: 'Defans', goals: 1, assists: 0, matchesPlayed: 26, rating: 7.8),
        ],
      ),
      Team(
        id: '42',
        name: 'Arsenal FC',
        shortName: 'Arsenal',
        crestUrl: 'https://media.api-sports.io/football/teams/42.png',
        league: 'Premier League',
        venue: 'Emirates Stadium',
        stats: const MatchStat(
          played: 29,
          won: 19,
          drawn: 7,
          lost: 3,
          goalsScored: 60,
          goalsConceded: 22,
          homePlayed: 14,
          homeWon: 11,
          homeDrawn: 2,
          homeLost: 1,
          homeGoalsScored: 34,
          homeGoalsConceded: 10,
          awayPlayed: 15,
          awayWon: 8,
          awayDrawn: 5,
          awayLost: 2,
          awayGoalsScored: 26,
          awayGoalsConceded: 12,
          avgPossession: 59.4,
          avgShotsPerGame: 15.2,
          avgShotsOnTarget: 5.9,
          cleanSheets: 13,
          recentForm: ['W', 'W', 'D', 'W', 'L'],
        ),
        squad: [
          Player(id: 'ars1', name: 'Bukayo Saka', position: 'Forvet', goals: 13, assists: 11, matchesPlayed: 27, rating: 8.4),
          Player(id: 'ars2', name: 'Martin Ødegaard', position: 'Orta Saha', goals: 8, assists: 9, matchesPlayed: 24, rating: 8.1),
          Player(id: 'ars3', name: 'Kai Havertz', position: 'Forvet', goals: 12, assists: 4, matchesPlayed: 28, rating: 7.7),
          Player(id: 'ars4', name: 'William Saliba', position: 'Defans', goals: 2, assists: 1, matchesPlayed: 29, rating: 8.2),
          Player(id: 'ars5', name: 'Declan Rice', position: 'Orta Saha', goals: 5, assists: 6, matchesPlayed: 29, rating: 8.0),
        ],
      ),
      Team(
        id: '645',
        name: 'Galatasaray SK',
        shortName: 'Galatasaray',
        crestUrl: 'https://media.api-sports.io/football/teams/645.png',
        league: 'Süper Lig',
        venue: 'RAMS Park',
        stats: const MatchStat(
          played: 26,
          won: 22,
          drawn: 3,
          lost: 1,
          goalsScored: 65,
          goalsConceded: 22,
          homePlayed: 13,
          homeWon: 12,
          homeDrawn: 1,
          homeLost: 0,
          homeGoalsScored: 39,
          homeGoalsConceded: 10,
          awayPlayed: 13,
          awayWon: 10,
          awayDrawn: 2,
          awayLost: 1,
          awayGoalsScored: 26,
          awayGoalsConceded: 12,
          avgPossession: 62.0,
          avgShotsPerGame: 17.1,
          avgShotsOnTarget: 6.9,
          cleanSheets: 12,
          recentForm: ['W', 'W', 'W', 'W', 'D'],
        ),
        squad: [
          Player(id: 'gs1', name: 'Victor Osimhen', position: 'Forvet', goals: 18, assists: 4, matchesPlayed: 20, rating: 8.6),
          Player(id: 'gs2', name: 'Mauro Icardi', position: 'Forvet', goals: 6, assists: 2, matchesPlayed: 10, rating: 7.9, isInjured: true, injuryReason: 'Ön çapraz bağ sakatlığı'),
          Player(id: 'gs3', name: 'Barış Alper Yılmaz', position: 'Forvet', goals: 11, assists: 7, matchesPlayed: 25, rating: 8.1),
          Player(id: 'gs4', name: 'Lucas Torreira', position: 'Orta Saha', goals: 2, assists: 3, matchesPlayed: 25, rating: 7.9),
          Player(id: 'gs5', name: 'Davinson Sánchez', position: 'Defans', goals: 3, assists: 1, matchesPlayed: 23, rating: 7.8),
        ],
      ),
      Team(
        id: '611',
        name: 'Fenerbahçe SK',
        shortName: 'Fenerbahçe',
        crestUrl: 'https://media.api-sports.io/football/teams/611.png',
        league: 'Süper Lig',
        venue: 'Şükrü Saracoğlu Stadyumu',
        stats: const MatchStat(
          played: 26,
          won: 20,
          drawn: 4,
          lost: 2,
          goalsScored: 61,
          goalsConceded: 21,
          homePlayed: 13,
          homeWon: 11,
          homeDrawn: 1,
          homeLost: 1,
          homeGoalsScored: 35,
          homeGoalsConceded: 9,
          awayPlayed: 13,
          awayWon: 9,
          awayDrawn: 3,
          awayLost: 1,
          awayGoalsScored: 26,
          awayGoalsConceded: 12,
          avgPossession: 58.7,
          avgShotsPerGame: 16.4,
          avgShotsOnTarget: 6.2,
          cleanSheets: 11,
          recentForm: ['W', 'W', 'D', 'W', 'W'],
        ),
        squad: [
          Player(id: 'fb1', name: 'Edin Džeko', position: 'Forvet', goals: 16, assists: 5, matchesPlayed: 25, rating: 8.0),
          Player(id: 'fb2', name: 'Dušan Tadić', position: 'Orta Saha', goals: 9, assists: 13, matchesPlayed: 26, rating: 8.3),
          Player(id: 'fb3', name: 'Allan Saint-Maximin', position: 'Forvet', goals: 6, assists: 8, matchesPlayed: 22, rating: 7.9),
          Player(id: 'fb4', name: 'Fred', position: 'Orta Saha', goals: 4, assists: 5, matchesPlayed: 23, rating: 8.1),
          Player(id: 'fb5', name: 'Jayden Oosterwolde', position: 'Defans', goals: 0, assists: 1, matchesPlayed: 12, rating: 7.4, isInjured: true, injuryReason: 'Diz bağı sakatlığı'),
        ],
      ),
      Team(
        id: '157',
        name: 'FC Bayern München',
        shortName: 'Bayern',
        crestUrl: 'https://media.api-sports.io/football/teams/157.png',
        league: 'Bundesliga',
        venue: 'Allianz Arena',
        stats: const MatchStat(
          played: 25,
          won: 18,
          drawn: 4,
          lost: 3,
          goalsScored: 72,
          goalsConceded: 27,
          homePlayed: 12,
          homeWon: 10,
          homeDrawn: 1,
          homeLost: 1,
          homeGoalsScored: 42,
          homeGoalsConceded: 11,
          awayPlayed: 13,
          awayWon: 8,
          awayDrawn: 3,
          awayLost: 2,
          awayGoalsScored: 30,
          awayGoalsConceded: 16,
          avgPossession: 65.1,
          avgShotsPerGame: 18.2,
          avgShotsOnTarget: 7.8,
          cleanSheets: 10,
          recentForm: ['W', 'W', 'W', 'L', 'W'],
        ),
        squad: [
          Player(id: 'bm1', name: 'Harry Kane', position: 'Forvet', goals: 27, assists: 9, matchesPlayed: 25, rating: 8.9),
          Player(id: 'bm2', name: 'Jamal Musiala', position: 'Orta Saha', goals: 12, assists: 7, matchesPlayed: 23, rating: 8.6),
          Player(id: 'bm3', name: 'Michael Olise', position: 'Forvet', goals: 10, assists: 8, matchesPlayed: 24, rating: 8.1),
          Player(id: 'bm4', name: 'Manuel Neuer', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 20, rating: 7.6),
          Player(id: 'bm5', name: 'Alphonso Davies', position: 'Defans', goals: 1, assists: 4, matchesPlayed: 22, rating: 7.7),
        ],
      ),
      Team(
        id: '505',
        name: 'Inter Milan',
        shortName: 'Inter',
        crestUrl: 'https://media.api-sports.io/football/teams/505.png',
        league: 'Serie A',
        venue: 'San Siro',
        stats: const MatchStat(
          played: 27,
          won: 19,
          drawn: 5,
          lost: 3,
          goalsScored: 62,
          goalsConceded: 24,
          homePlayed: 13,
          homeWon: 10,
          homeDrawn: 2,
          homeLost: 1,
          homeGoalsScored: 33,
          homeGoalsConceded: 10,
          awayPlayed: 14,
          awayWon: 9,
          awayDrawn: 3,
          awayLost: 2,
          awayGoalsScored: 29,
          awayGoalsConceded: 14,
          avgPossession: 57.8,
          avgShotsPerGame: 15.6,
          avgShotsOnTarget: 5.8,
          cleanSheets: 13,
          recentForm: ['W', 'W', 'D', 'W', 'W'],
        ),
        squad: [
          Player(id: 'int1', name: 'Lautaro Martínez', position: 'Forvet', goals: 17, assists: 5, matchesPlayed: 25, rating: 8.3),
          Player(id: 'int2', name: 'Marcus Thuram', position: 'Forvet', goals: 13, assists: 6, matchesPlayed: 26, rating: 8.0),
          Player(id: 'int3', name: 'Nicolò Barella', position: 'Orta Saha', goals: 4, assists: 8, matchesPlayed: 24, rating: 8.2),
          Player(id: 'int4', name: 'Hakan Çalhanoğlu', position: 'Orta Saha', goals: 8, assists: 5, matchesPlayed: 23, rating: 8.1),
          Player(id: 'int5', name: 'Alessandro Bastoni', position: 'Defans', goals: 1, assists: 3, matchesPlayed: 25, rating: 7.9),
        ],
      ),
      Team(
        id: '549',
        name: 'Beşiktaş',
        shortName: 'Beşiktaş',
        crestUrl: 'https://media.api-sports.io/football/teams/549.png',
        league: 'Süper Lig',
        venue: 'Tüpraş Stadyumu',
        stats: const MatchStat(
          played: 26,
          won: 14,
          drawn: 6,
          lost: 6,
          goalsScored: 44,
          goalsConceded: 27,
          homePlayed: 13,
          homeWon: 8,
          homeDrawn: 3,
          homeLost: 2,
          homeGoalsScored: 26,
          homeGoalsConceded: 12,
          awayPlayed: 13,
          awayWon: 6,
          awayDrawn: 3,
          awayLost: 4,
          awayGoalsScored: 18,
          awayGoalsConceded: 15,
          avgPossession: 56.4,
          avgShotsPerGame: 14.2,
          avgShotsOnTarget: 5.3,
          cleanSheets: 9,
          recentForm: ['W', 'W', 'D', 'L', 'W'],
        ),
        squad: [
          Player(id: 'bes1', name: 'Ciro Immobile', position: 'Forvet', goals: 12, assists: 3, matchesPlayed: 21, rating: 8.1),
          Player(id: 'bes2', name: 'Rafa Silva', position: 'Orta Saha', goals: 9, assists: 7, matchesPlayed: 24, rating: 8.3),
          Player(id: 'bes3', name: 'Semih Kılıçsoy', position: 'Forvet', goals: 7, assists: 4, matchesPlayed: 22, rating: 7.8),
          Player(id: 'bes4', name: 'Mert Günok', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 23, rating: 7.6),
        ],
      ),
      Team(
        id: '607',
        name: 'Trabzonspor',
        shortName: 'Trabzonspor',
        crestUrl: 'https://media.api-sports.io/football/teams/607.png',
        league: 'Süper Lig',
        venue: 'Papara Park',
        stats: const MatchStat(
          played: 26,
          won: 11,
          drawn: 8,
          lost: 7,
          goalsScored: 39,
          goalsConceded: 31,
          homePlayed: 13,
          homeWon: 7,
          homeDrawn: 4,
          homeLost: 2,
          homeGoalsScored: 24,
          homeGoalsConceded: 14,
          awayPlayed: 13,
          awayWon: 4,
          awayDrawn: 4,
          awayLost: 5,
          awayGoalsScored: 15,
          awayGoalsConceded: 17,
          avgPossession: 53.8,
          avgShotsPerGame: 13.5,
          avgShotsOnTarget: 4.8,
          cleanSheets: 8,
          recentForm: ['D', 'W', 'W', 'L', 'D'],
        ),
        squad: [
          Player(id: 'tra1', name: 'Simon Banza', position: 'Forvet', goals: 11, assists: 2, matchesPlayed: 19, rating: 7.9),
          Player(id: 'tra2', name: 'Edin Višća', position: 'Forvet', goals: 5, assists: 8, matchesPlayed: 23, rating: 7.8),
          Player(id: 'tra3', name: 'Uğurcan Çakır', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 26, rating: 8.0),
        ],
      ),
      Team(
        id: '40',
        name: 'Liverpool',
        shortName: 'Liverpool',
        crestUrl: 'https://media.api-sports.io/football/teams/40.png',
        league: 'Premier League',
        venue: 'Anfield',
        stats: const MatchStat(
          played: 28,
          won: 21,
          drawn: 4,
          lost: 3,
          goalsScored: 67,
          goalsConceded: 26,
          homePlayed: 14,
          homeWon: 12,
          homeDrawn: 1,
          homeLost: 1,
          homeGoalsScored: 37,
          homeGoalsConceded: 11,
          awayPlayed: 14,
          awayWon: 9,
          awayDrawn: 3,
          awayLost: 2,
          awayGoalsScored: 30,
          awayGoalsConceded: 15,
          avgPossession: 61.2,
          avgShotsPerGame: 16.4,
          avgShotsOnTarget: 6.5,
          cleanSheets: 12,
          recentForm: ['W', 'W', 'W', 'D', 'W'],
        ),
        squad: [
          Player(id: 'liv1', name: 'Mohamed Salah', position: 'Forvet', goals: 21, assists: 13, matchesPlayed: 27, rating: 8.7),
          Player(id: 'liv2', name: 'Luis Díaz', position: 'Forvet', goals: 11, assists: 4, matchesPlayed: 26, rating: 8.0),
          Player(id: 'liv3', name: 'Virgil van Dijk', position: 'Defans', goals: 2, assists: 1, matchesPlayed: 28, rating: 8.2),
          Player(id: 'liv4', name: 'Alisson Becker', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 18, rating: 7.9),
        ],
      ),
      Team(
        id: '49',
        name: 'Chelsea',
        shortName: 'Chelsea',
        crestUrl: 'https://media.api-sports.io/football/teams/49.png',
        league: 'Premier League',
        venue: 'Stamford Bridge',
        stats: const MatchStat(
          played: 28,
          won: 14,
          drawn: 7,
          lost: 7,
          goalsScored: 53,
          goalsConceded: 37,
          homePlayed: 14,
          homeWon: 8,
          homeDrawn: 4,
          homeLost: 2,
          homeGoalsScored: 29,
          homeGoalsConceded: 16,
          awayPlayed: 14,
          awayWon: 6,
          awayDrawn: 3,
          awayLost: 5,
          awayGoalsScored: 24,
          awayGoalsConceded: 21,
          avgPossession: 58.5,
          avgShotsPerGame: 14.8,
          avgShotsOnTarget: 5.6,
          cleanSheets: 8,
          recentForm: ['W', 'L', 'W', 'D', 'W'],
        ),
        squad: [
          Player(id: 'che1', name: 'Cole Palmer', position: 'Orta Saha', goals: 15, assists: 9, matchesPlayed: 26, rating: 8.5),
          Player(id: 'che2', name: 'Nicolas Jackson', position: 'Forvet', goals: 10, assists: 4, matchesPlayed: 24, rating: 7.7),
          Player(id: 'che3', name: 'Moisés Caicedo', position: 'Orta Saha', goals: 1, assists: 3, matchesPlayed: 27, rating: 7.9),
        ],
      ),
      Team(
        id: '530',
        name: 'Atletico Madrid',
        shortName: 'Atletico',
        crestUrl: 'https://media.api-sports.io/football/teams/530.png',
        league: 'La Liga',
        venue: 'Cívitas Metropolitano',
        stats: const MatchStat(
          played: 28,
          won: 17,
          drawn: 7,
          lost: 4,
          goalsScored: 49,
          goalsConceded: 21,
          homePlayed: 14,
          homeWon: 10,
          homeDrawn: 3,
          homeLost: 1,
          homeGoalsScored: 30,
          homeGoalsConceded: 9,
          awayPlayed: 14,
          awayWon: 7,
          awayDrawn: 4,
          awayLost: 3,
          awayGoalsScored: 19,
          awayGoalsConceded: 12,
          avgPossession: 53.0,
          avgShotsPerGame: 13.9,
          avgShotsOnTarget: 5.2,
          cleanSheets: 13,
          recentForm: ['W', 'W', 'D', 'W', 'W'],
        ),
        squad: [
          Player(id: 'atm1', name: 'Antoine Griezmann', position: 'Forvet', goals: 12, assists: 8, matchesPlayed: 26, rating: 8.3),
          Player(id: 'atm2', name: 'Julián Álvarez', position: 'Forvet', goals: 11, assists: 3, matchesPlayed: 25, rating: 8.0),
          Player(id: 'atm3', name: 'Jan Oblak', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 28, rating: 8.1),
        ],
      ),
      Team(
        id: '168',
        name: 'Bayer Leverkusen',
        shortName: 'Leverkusen',
        crestUrl: 'https://media.api-sports.io/football/teams/168.png',
        league: 'Bundesliga',
        venue: 'BayArena',
        stats: const MatchStat(
          played: 26,
          won: 16,
          drawn: 7,
          lost: 3,
          goalsScored: 58,
          goalsConceded: 32,
          homePlayed: 13,
          homeWon: 9,
          homeDrawn: 3,
          homeLost: 1,
          homeGoalsScored: 33,
          homeGoalsConceded: 15,
          awayPlayed: 13,
          awayWon: 7,
          awayDrawn: 4,
          awayLost: 2,
          awayGoalsScored: 25,
          awayGoalsConceded: 17,
          avgPossession: 60.1,
          avgShotsPerGame: 16.0,
          avgShotsOnTarget: 6.2,
          cleanSheets: 8,
          recentForm: ['W', 'W', 'D', 'W', 'D'],
        ),
        squad: [
          Player(id: 'lev1', name: 'Florian Wirtz', position: 'Orta Saha', goals: 11, assists: 10, matchesPlayed: 25, rating: 8.6),
          Player(id: 'lev2', name: 'Victor Boniface', position: 'Forvet', goals: 10, assists: 3, matchesPlayed: 18, rating: 8.0),
          Player(id: 'lev3', name: 'Granit Xhaka', position: 'Orta Saha', goals: 2, assists: 5, matchesPlayed: 26, rating: 8.1),
        ],
      ),
      Team(
        id: '489',
        name: 'AC Milan',
        shortName: 'Milan',
        crestUrl: 'https://media.api-sports.io/football/teams/489.png',
        league: 'Serie A',
        venue: 'San Siro',
        stats: const MatchStat(
          played: 27,
          won: 14,
          drawn: 6,
          lost: 7,
          goalsScored: 47,
          goalsConceded: 31,
          homePlayed: 14,
          homeWon: 9,
          homeDrawn: 3,
          homeLost: 2,
          homeGoalsScored: 28,
          homeGoalsConceded: 13,
          awayPlayed: 13,
          awayWon: 5,
          awayDrawn: 3,
          awayLost: 5,
          awayGoalsScored: 19,
          awayGoalsConceded: 18,
          avgPossession: 55.2,
          avgShotsPerGame: 14.5,
          avgShotsOnTarget: 5.1,
          cleanSheets: 9,
          recentForm: ['W', 'L', 'W', 'W', 'D'],
        ),
        squad: [
          Player(id: 'mil1', name: 'Christian Pulisic', position: 'Forvet', goals: 11, assists: 7, matchesPlayed: 25, rating: 8.2),
          Player(id: 'mil2', name: 'Rafael Leão', position: 'Forvet', goals: 8, assists: 8, matchesPlayed: 24, rating: 8.0),
          Player(id: 'mil3', name: 'Theo Hernández', position: 'Defans', goals: 4, assists: 5, matchesPlayed: 24, rating: 7.9),
          Player(id: 'mil4', name: 'Mike Maignan', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 26, rating: 7.8),
        ],
      ),
      Team(
        id: '496',
        name: 'Juventus',
        shortName: 'Juventus',
        crestUrl: 'https://media.api-sports.io/football/teams/496.png',
        league: 'Serie A',
        venue: 'Allianz Stadium',
        stats: const MatchStat(
          played: 27,
          won: 13,
          drawn: 12,
          lost: 2,
          goalsScored: 45,
          goalsConceded: 20,
          homePlayed: 14,
          homeWon: 7,
          homeDrawn: 7,
          homeLost: 0,
          homeGoalsScored: 24,
          homeGoalsConceded: 10,
          awayPlayed: 13,
          awayWon: 6,
          awayDrawn: 5,
          awayLost: 2,
          awayGoalsScored: 21,
          awayGoalsConceded: 10,
          avgPossession: 58.0,
          avgShotsPerGame: 13.8,
          avgShotsOnTarget: 4.9,
          cleanSheets: 14,
          recentForm: ['W', 'D', 'W', 'D', 'W'],
        ),
        squad: [
          Player(id: 'juv1', name: 'Dušan Vlahović', position: 'Forvet', goals: 12, assists: 2, matchesPlayed: 24, rating: 7.9),
          Player(id: 'juv2', name: 'Kenan Yıldız', position: 'Forvet', goals: 6, assists: 5, matchesPlayed: 26, rating: 8.1),
          Player(id: 'juv3', name: 'Bremer', position: 'Defans', goals: 0, assists: 0, matchesPlayed: 7, rating: 7.8, isInjured: true, injuryReason: 'Çapraz bağ'),
        ],
      ),
      Team(
        id: '85',
        name: 'Paris Saint Germain',
        shortName: 'PSG',
        crestUrl: 'https://media.api-sports.io/football/teams/85.png',
        league: 'Ligue 1',
        venue: 'Parc des Princes',
        stats: const MatchStat(
          played: 25,
          won: 18,
          drawn: 6,
          lost: 1,
          goalsScored: 60,
          goalsConceded: 22,
          homePlayed: 12,
          homeWon: 10,
          homeDrawn: 2,
          homeLost: 0,
          homeGoalsScored: 34,
          homeGoalsConceded: 10,
          awayPlayed: 13,
          awayWon: 8,
          awayDrawn: 4,
          awayLost: 1,
          awayGoalsScored: 26,
          awayGoalsConceded: 12,
          avgPossession: 65.4,
          avgShotsPerGame: 16.8,
          avgShotsOnTarget: 6.9,
          cleanSheets: 10,
          recentForm: ['W', 'W', 'W', 'D', 'W'],
        ),
        squad: [
          Player(id: 'psg1', name: 'Bradley Barcola', position: 'Forvet', goals: 13, assists: 4, matchesPlayed: 23, rating: 8.2),
          Player(id: 'psg2', name: 'Ousmane Dembélé', position: 'Forvet', goals: 7, assists: 7, matchesPlayed: 22, rating: 8.1),
          Player(id: 'psg3', name: 'Achraf Hakimi', position: 'Defans', goals: 3, assists: 5, matchesPlayed: 22, rating: 8.0),
          Player(id: 'psg4', name: 'Gianluigi Donnarumma', position: 'Kaleci', goals: 0, assists: 0, matchesPlayed: 21, rating: 7.7),
        ],
      ),
    ];
  }
}

